# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-10 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='projects_pic'),
        ),
    ]
