# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-06-27 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projectimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.get_path_project),
        ),
        migrations.AlterField(
            model_name='projectimg',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=projects.models.get_path_img),
        ),
    ]
