# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-05 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_remove_project_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectimg',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
