# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-11 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_projectimg_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImgOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='projectimg',
            name='order',
        ),
        migrations.AddField(
            model_name='imgorder',
            name='img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='projects.ProjectImg'),
        ),
    ]
