# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-18 18:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('level_dec', models.IntegerField()),
                ('level_procentage', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='skill',
            name='skillGrouop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.SkillGroup'),
        ),
    ]
