# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-22 16:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_auto_20180719_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='endDate',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level_dec',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='level_procentage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='skill',
            name='skillGrouop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill', to='skills.SkillGroup'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='startDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
