# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-22 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0008_auto_20180722_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillgroup',
            name='importance',
            field=models.IntegerField(default=0),
        ),
    ]
