# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-22 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0009_skillgroup_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='add_info_1',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='skill',
            name='add_info_2',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
