# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-07-22 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0010_auto_20180722_2132'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillgroup',
            name='display_width',
            field=models.CharField(choices=[('full', 'full'), ('half', 'half')], default='half', max_length=20),
        ),
    ]
