# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-05 11:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0011_skillgroup_display_width'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_description', models.TextField(max_length=500)),
                ('img', models.ImageField(blank=True, null=True, upload_to='about_img/')),
            ],
        ),
    ]
