# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-05 11:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0012_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='about_description',
            new_name='description',
        ),
    ]
