# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-09-05 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0013_auto_20180905_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(max_length=1500),
        ),
    ]
